name: Suying666-Auto-Checkin
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    name: Suying666-Checkin by GitHub Actions
    runs-on: ubuntu-18.04

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v3

      - name: 2. setup python3...
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: 3. do checkin...
        run: python index.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}

      - name: 4. update github repository...
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name "bot"
          git add .
          git commit -m "auto-update"
          git push -f
