name: Suying666-Auto-Checkin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
permissions: write-all
jobs:
  checkin:
    name: Suying666-Checkin
    runs-on: ubuntu-22.04

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v3

      - name: 2. setup python3...
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: 3. do checkin...
        run: python index.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}

      - name: 4. commit...
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "auto-checkin"

      - name: 5. push changes to repository...
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
